//
//  Counries.swift
//  PK CRM
//
//  Created by Κωνσταντίνος Πατσίκας on 21/11/23.
//

import Foundation

class Counries{
    static let countries: [Int: String] = [
        // European countries
        0: "Greece",
        1: "Cyprus",
        2: "Albania",
        3: "Andorra",
        4: "Armenia",
        5: "Austria",
        6: "Azerbaijan",
        7: "Belarus",
        8: "Belgium",
        9: "Bosnia and Herzegovina",
        10: "Bulgaria",
        11: "Croatia",
        12: "Czech Republic",
        13: "Denmark",
        14: "Estonia",
        15: "Finland",
        16: "France",
        17: "Georgia",
        18: "Germany",
        19: "Hungary",
        20: "Iceland",
        21: "Ireland",
        22: "Italy",
        23: "Kazakhstan",
        24: "Kosovo",
        25: "Latvia",
        26: "Liechtenstein",
        27: "Lithuania",
        28: "Luxembourg",
        29: "Malta",
        30: "Moldova",
        31: "Monaco",
        32: "Montenegro",
        33: "Netherlands",
        34: "North Macedonia",
        35: "Norway",
        36: "Poland",
        37: "Portugal",
        38: "Romania",
        39: "Russia",
        40: "San Marino",
        41: "Serbia",
        42: "Slovakia",
        43: "Slovenia",
        44: "Spain",
        45: "Sweden",
        46: "Switzerland",
        47: "Turkey",
        48: "Ukraine",
        49: "United Kingdom",
        50: "Vatican City",
        
        // Asian countries
        51: "Afghanistan",
        52: "Bahrain",
        53: "Bangladesh",
        54: "Bhutan",
        55: "Brunei",
        56: "Cambodia",
        57: "China",
        58: "India",
        59: "Indonesia",
        60: "Iran",
        61: "Iraq",
        62: "Israel",
        63: "Japan",
        64: "Jordan",
        65: "Kuwait",
        66: "Kyrgyzstan",
        67: "Laos",
        68: "Lebanon",
        69: "Malaysia",
        70: "Maldives",
        71: "Mongolia",
        72: "Myanmar",
        73: "Nepal",
        74: "North Korea",
        75: "Oman",
        76: "Pakistan",
        77: "Palestine",
        78: "Philippines",
        79: "Qatar",
        80: "Saudi Arabia",
        81: "Singapore",
        82: "South Korea",
        83: "Sri Lanka",
        84: "Syria",
        85: "Taiwan",
        86: "Tajikistan",
        87: "Thailand",
        88: "Timor-Leste",
        89: "Turkmenistan",
        90: "United Arab Emirates",
        91: "Uzbekistan",
        92: "Vietnam",
        93: "Yemen",
        
        // African countries
        94: "Algeria",
        95: "Angola",
        96: "Benin",
        97: "Botswana",
        98: "Burkina Faso",
        99: "Burundi",
        100: "Cabo Verde",
        101: "Cameroon",
        102: "Central African Republic",
        103: "Chad",
        104: "Comoros",
        105: "Congo",
        106: "Djibouti",
        107: "Egypt",
        108: "Equatorial Guinea",
        109: "Eritrea",
        110: "Eswatini",
        111: "Ethiopia",
        112: "Gabon",
        113: "Gambia",
        114: "Ghana",
        115: "Guinea",
        116: "Guinea-Bissau",
        117: "Ivory Coast",
        118: "Kenya",
        119: "Lesotho",
        120: "Liberia",
        121: "Libya",
        122: "Madagascar",
        123: "Malawi",
        124: "Mali",
        125: "Mauritania",
        126: "Mauritius",
        127: "Morocco",
        128: "Mozambique",
        129: "Namibia",
        130: "Niger",
        131: "Nigeria",
        132: "Rwanda",
        133: "Sao Tome and Principe",
        134: "Senegal",
        135: "Seychelles",
        136: "Sierra Leone",
        137: "Somalia",
        138: "South Africa",
        139: "South Sudan",
        140: "Sudan",
        141: "Tanzania",
        142: "Togo",
        143: "Tunisia",
        144: "Uganda",
        145: "Zambia",
        146: "Zimbabwe",
        
        // Oceania countries
        147: "Australia",
        148: "Fiji",
        149: "Kiribati",
        150: "Marshall Islands",
        151: "Micronesia",
        152: "Nauru",
        153: "New Zealand",
        154: "Palau",
        155: "Papua New Guinea",
        156: "Samoa",
        157: "Solomon Islands",
        158: "Tonga",
        159: "Tuvalu",
        160: "Vanuatu",
        
        // North American countries
        161: "Antigua and Barbuda",
        162: "Bahamas",
        163: "Barbados",
        164: "Belize",
        165: "Canada",
        166: "Costa Rica",
        167: "Cuba",
        168: "Dominica",
        169: "Dominican Republic",
        170: "El Salvador",
        171: "Grenada",
        172: "Guatemala",
        173: "Haiti",
        174: "Honduras",
        175: "Jamaica",
        176: "Mexico",
        177: "Nicaragua",
        178: "Panama",
        179: "Saint Kitts and Nevis",
        180: "Saint Lucia",
        181: "Saint Vincent and the Grenadines",
        182: "Trinidad and Tobago",
        183: "United States",
        
        // South American countries
        184: "Argentina",
        185: "Bolivia",
        186: "Brazil",
        187: "Chile",
        188: "Colombia",
        189: "Ecuador",
        190: "Guyana",
        191: "Paraguay",
        192: "Peru",
        193: "Suriname",
        194: "Uruguay",
        195: "Venezuela"
        
    ]
}
